### ISSUE TITLE
LateInitializationError: Local 'dylib' has not been initialized.

### ISSUE THREAD

**Issue by maticla** [insinfo/pdfium_bindings#4]
I'm getting this error when trying to run High-level example:

```
[VERBOSE-2:dart_isolate.cc(1097)] Unhandled exception:
LateInitializationError: Local 'dylib' has not been initialized.
#0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:197:5)
#1      new PdfiumWrap
pdfium_wrap.dart:41
#2      pdfiumRoutine
test_view.dart:19
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

I am spawning an Isolate in initState() and then running the High-level example in the Isolate function.

Am I missing something?  Running on Simulator iPhone 14 with iOS 16.4, Flutter SDK 3.10.1

**Comment by insinfo** [comment]
you have to have pdfium dynamic library for ios in your project
https://github.com/paulocoutinhox/pdfium-lib
https://medium.com/@prabhu_irl/getting-started-with-dlib-on-ios-5e66d77380d#:~:text=Adding%20dlib%20to%20your%20xcode%20project&text=Copy%20the%20'dlib'%20folder%20from,section%20of%20ur%20Xcode%20project.
I don't have much knowledge of ios to help
